### PR TITLE
Yet more support for modelmeta index_netcdf

### PR DESCRIPTION
**Pull request by rod-glover**
Add auto-prefixed properties. 
Auto-prefixed properties are accessed by the `prefixed` property, e.g., `cf.prefixed.model_id`.
Auto-prefixed have an automatically computed prefix added to the base property name (e.g., `cf.prefixed.model_id` --> `cf.forcing_driving_model_id`) before it is accessed. Prefix is based on the content of the CFDataset file (e.g., a hydromodel file forced by downscaled GCM data).

### CODE REVIEW

**Comment by jameshiebert** [comment]
Would you be willing to discuss and weigh the advantages/disadvantages of this approach? On one hand, I see how it could be convenient to programattically determine those prefixes. But on the other, it seems like it's make the code super meta, in order to replace a [5-case switch statement](https://github.com/pacificclimate/nchelpers/pull/19/files#diff-45945a0da0dbdc1f12f63774e785e2b5L616). Is it worth the additional complexity? How will these auto-prefixes be used in practice?

**Comment by rod-glover** [comment]
Happy to discuss. 

Specifically, auto-prefixed attributes are already being used now in the unified metadata values, which now [return (some) auto-prefixed values](https://github.com/pacificclimate/nchelpers/pull/19/files#diff-45945a0da0dbdc1f12f63774e785e2b5R534). Also as you noted, in `ensemble_member`. All of these in turn make index_netcdf work correctly with all types of files (raw GCM, downscaled, hydromodel, climo).

In general, auto-prefixing is widely applicable, since there are literally dozens of prefixed variants of "base" attributes in the metadata standard. Any code that needs to handle multiple file types will want to take advantage of auto-prefix.

And ... I just noticed that I transferred a condition appropriate only to `ensemble_member` to the general case of auto-prefixing, and will correct that if we decide to adopt auto-prefix generally.

**Comment by rod-glover** [comment]
I also see that [`_cmor_type_filename_components`](https://github.com/pacificclimate/nchelpers/blob/master/nchelpers/__init__.py#L639) can be simplified with auto-prefixing.

**Comment by jameshiebert** [comment]
Yeah, I can see how continue to eliminate those long switches like [_cmor_type_filename_components](https://github.com/pacificclimate/nchelpers/blob/master/nchelpers/__init__.py#L639) is a good thing. I guess the thing that I'm having trouble with is, as a user, what does `.prefixed.some_attribute` mean? And the answer is: "it depends on the context". So it doesn't help reduce the cognitive load of writing/reading/using the code, because you still have to think deeply about what the context is in which it's being used. At least as far as I understand it now.

If you were to concisely describe the meaning of the `prefixed` attribute, what would that be? Properties that relate to some ancestor of the dataset in question? 

I'll trust your judgement to keep going down this road if you think that it's the best path forward. But I wanted to say that it doesn't come across as an obvious simplification to me (at first read).

One aside: should the ``AutoPrefix`` class also have a  __setattr__? Could this be handled through a descriptor on the ``CFDataset`` class?

**Comment by rod-glover** [comment]
Excellent questions and you are right, this feature as it stands calls for more thought than is desirable. But maybe the clarification and renaming below improves matters sufficiently?

The meaning of `prefixed` is:
"Attribute describing the original input GCM data used by the program that generated this data."

Therefore `AutoPrefix` should be renamed `AutoGcmPrefix`, `prefixed` should be renamed `gcm`, and this more precise and limited meaning added to the documentation.
Attributes describing the input GCM data would then look like, e.g., `cf.gcm.model_id`.

I still think it is worth doing this way, but am open to alternatives / further critiques.

**Comment by rod-glover** [comment]
Yes, `AutoGcmPrefix` should have a `setattr`. It's not used anywhere yet, but that would lend a natural and helpful symmetry. 

We might consider adding `setattr` to `UnifiedMetadata` too, although as originally defined in the R code that inspires it, it was a read-only feature.

**Comment by rod-glover** [comment]
@jameshiebert, I made the changes discussed above. See if that reduces the issues you mentioned. I'd like to get this merged and published, so that the modelmeta indexing code that depends on it can start passing tests in Travis.

Let's discuss if you still have issues with this.

**Comment by jameshiebert** [comment]
Yes, I think that this helps to make it a little more concrete as to how the prefixing is intended to be used. I'm happy to go ahead and merge this.

**Pull request merged**
