### PR TITLE
Raise more helpful exceptions when attributes are missing

### LINKED ISSUE #24: Unhelpful exception raised when getting unified metadata attr and project_id missing
`nchelpers` raises an AttributeError exception with no useful information when getting any unified metadata attribute (defined or otherwise) from a file that does not have the `project_id` attribute defined.

Also does the same thing if `project_id` is defined but metadata target attribute is missing.

### PR DESCRIPTION
**Pull request by rod-glover**
Fixes #24 

Also sneaking in a fix for `climatology_bounds_var_name`, which tried to get time units (attribute) from the time bounds variable, and failed in this unhelpful way because, generally speaking, units are on the time variable proper, not the bounds variable.

### CODE REVIEW

**Comment by rod-glover** [comment]
The changes in this PR 
(a) are technically breaking changes, since they change the exceptions that can be raised by the package, and
(b) have an algorithmic effect on some client packages because of the change to  `climatology_bounds_var_name`

All unit tests for clients (`climate-explorer-backend`, `modelmeta` of this package have been run, with success, strongly suggesting that the potential breakage is not actual.

**Comment by corviday** [comment]
It looks reasonable and thought-out to me. 

Question: does netcdf4 do anything about attribute errors besides catch and rethrow them? Is there any _desirable_ functionality we miss out on by switching to our own error types (to avoid the undesirable functionality of losing helpful error messages)? Any sort of recovery or processing?

It seems like all we'd really want to do in these cases is stop the process and alert the user; missing attributes isn't really the kind of error you want to try and take your best guess at and soldier on. But I do wonder if netcdf4 had _some_ kind of reason to do things the unintuitive way it did?

**Comment by rod-glover** [comment]
AFAICT, there is no useful functionality added by netCDF4's behaviour here. 

Given the loss of information (both message and stack trace context) when it reraises, I suspect this is an unavoidable result of the Python wrapping of the underlying netCDF C library, and not a specifically desired add-in.

**Comment by corviday** [comment]
LGTM!

**Pull request merged**
